### ISSUE TITLE
서버&클라 통신 모델  확보

### ISSUE THREAD

**Issue by ssorae** [Team-EnterSon/TESTREES#2]
Unity <-> .Net Core 사이의 통신 모델을 확보하기 위한 R&D를 진행합니다.
실제 작동하는 유니티 샘플 단톡방 구현까지가 목표입니다.

**Comment by wsong0101** [comment]
별도 브랜치로 작업중.
https://github.com/wsong0101/.NET-Core-2.0-Simple-TCP-Server
